### PR TITLE
Fix #71 Adopt 2018-12 release in the build

### LINKED ISSUE #71: Set default target to released 2018-12
Now, as 2018-12 should be officially released, we should build on this released version.

### PR DESCRIPTION
**Pull request by cdamus**
Rework the ‘photon’ release TP as 2018-12 and update the build to use the release target.

### CODE REVIEW

**Comment by tortmayr** [comment]
Seems like the <i>nightly</i> and <i>release</i> target definitions are out of sync.
The release target misses the plugins:

- org.eclipse.equinox.transforms.hook
- org.eclipse.equinox.transforms.xslt

**Comment by cdamus** [comment]
Oo!  Good catch.

**Comment by tortmayr** [comment]
Oh and our (not so) nightly target is still based on 2018-09 :grimacing:

**Comment by cdamus** [comment]
That's technically out of scope 😝 but easy to fix.

**Comment by cdamus** [comment]
Okay, so I **finally** figured out why the Tycho compiler couldn't find any SWT APIs in the UI bundles using Eclipse 2018-12 release, by turning on all possible debug output and sifting through it.

The problem was that in this release, Eclipse dropped support for the Windows 32-bit platform (only 64-bit now supported).  This meant that the 32-bit SWT fragment is no longer available.  But, our POM was still configuring the target platform for both 32- and 64-bit Windows.  Because the 32-bit platform was listed first, this was the one that the compiler would use to resolve the compile-time classpath, and so the SWT API wouldn't end up on the classpath because the API is in the platform-specific fragments, not the main SWT bundle.  Any attempt to build the RCP package would eventually have failed anyways because of the failure to resolve the 32-bit platform, but the compile-time errors got to it first.

Anyways, there has been enough back-and-forth in commits on this pull request that I thought it best just to squash everything into one commit now to make it as clean as possible.

**Pull request merged**
