### PR TITLE
Fix RCP feature name, inlcude Papyrus Compare and add Compare pre-configuration

### PR DESCRIPTION
**Pull request by planger**
As this is probably one of the last changes, we merge before "releasing" UMLLight, please test this change also quite in detail (also with the built product). Thanks!

### CODE REVIEW

**Comment by planger** [comment]
Strange, the CI didn't correctly report the build result:
https://travis-ci.org/eclipsesource/papyrus-umllight/builds/485416013

**Comment by tortmayr** [comment]
> Strange, the CI didn't correctly report the build result:
> https://travis-ci.org/eclipsesource/papyrus-umllight/builds/485416013

I did close and reopen the PR to retrigger the build. Maybe it works now

**Comment by planger** [comment]
Good idea, this seem to have worked! Or it was my restart of the build, who knows :) Anyway, not this is ready for review. Thanks!

**Comment by tortmayr** [comment]
I did try a manual restart of the build before as well but it had no affect. At least now we now that reopening the pull request works if we run into that issue again in the future :wink:

**Review by tortmayr — COMMENTED** [review]
Looks good but I found some issues with the build product/p2 repository:

When trying to compare UML Light models in the built product the default Eclipse text compare is used. I guess we also need to  include the EMF Compare SDK  in the UML Light feature (since its not shipped with PapyrusCompare anymore).

Installing UML Light from the (local) update-site into a Eclipse Modeling Tools 2018-12 package works fine but without installing the core Papyrus editor its not possible to create diagrams. So maybe we should include Papyrus for UML as well?

**Comment by tortmayr** [comment]
Apparently my local maven environment was corrupted and the build product didn't have the latest changes. After cleaning my .m2 folder the build product now works as expected.

**Review by tortmayr — APPROVED** [review]

**Comment by planger** [comment]
Thanks a lot!

**Pull request merged**
